// ข้อมูลสถานีขนส่ง บขส. และจุดจอดรถโดยสารทั้งหมดใน 3 จังหวัดชายแดนภาคใต้
// พิกัด GPS จาก Google Maps / Longdo Map / OpenStreetMap

export type StationType = 'major' | 'minor' | 'local_stop';
export type Province = 'pattani' | 'yala' | 'narathiwat';

export interface BusStation {
  id: string;
  name_th: string;
  name_en: string;
  province: Province;
  district: string;
  type: StationType;
  lat: number;
  lng: number;
  description_th: string;
  description_en: string;
  connections: string[]; // IDs of connected stations
}

export const BUS_STATIONS: BusStation[] = [
  // ══════════════════════════════════════════════
  //  จังหวัดปัตตานี (PATTANI)
  // ══════════════════════════════════════════════

  // ── สถานีหลัก ──
  {
    id: 'PTN-MAIN',
    name_th: 'สถานีขนส่งผู้โดยสาร จ.ปัตตานี (บขส. ปัตตานี)',
    name_en: 'Pattani Bus Terminal (BKS Pattani)',
    province: 'pattani',
    district: 'อ.เมืองปัตตานี',
    type: 'major',
    lat: 6.8530,
    lng: 101.2980,
    description_th: 'จุดจอดรถทัวร์กรุงเทพฯ รถบัสข้ามจังหวัด และรถตู้หลัก',
    description_en: 'Bangkok coach, inter-provincial bus & main van terminal',
    connections: ['PTN-PSU', 'PTN-KPH', 'PTN-NJK', 'YLA-MAIN', 'NRW-MAIN'],
  },

  // ── สถานีย่อย / คิวรถ ──
  {
    id: 'PTN-PSU',
    name_th: 'จุดจอด บขส. ย่อย ปัตตานี (หน้า ม.อ.ปัตตานี)',
    name_en: 'PSU Pattani Sub-Terminal',
    province: 'pattani',
    district: 'อ.เมืองปัตตานี',
    type: 'minor',
    lat: 6.8866,
    lng: 101.2397,
    description_th: 'จุดจอดขึ้น-ลงรถทัวร์/รถตู้หลักสำหรับนักศึกษาและคนในเมือง',
    description_en: 'Sub-stop for students & locals near PSU Pattani campus',
    connections: ['PTN-MAIN'],
  },
  {
    id: 'PTN-KPH',
    name_th: 'คิวรถตู้ปัตตานี (ใกล้สถานีรถไฟโคกโพธิ์)',
    name_en: 'Khok Pho Van Terminal (Near Train Station)',
    province: 'pattani',
    district: 'อ.โคกโพธิ์',
    type: 'minor',
    lat: 6.7288,
    lng: 101.0942,
    description_th: 'จุดเชื่อมต่อระหว่างรถไฟกับรถตู้ไปเมืองปัตตานี',
    description_en: 'Train-van interchange to Pattani city',
    connections: ['PTN-MAIN', 'YLA-MAIN'],
  },
  {
    id: 'PTN-SBR',
    name_th: 'คิวรถตู้/รถโดยสารประจำทาง อ.สายบุรี',
    name_en: 'Saiburi Van & Bus Stop',
    province: 'pattani',
    district: 'อ.สายบุรี',
    type: 'minor',
    lat: 6.7012,
    lng: 101.5279,
    description_th: 'รถตู้ไปปัตตานี, นราธิวาส, นราฯ-สุไหงโก-ลก',
    description_en: 'Van hub to Pattani, Narathiwat & Sungai Kolok',
    connections: ['PTN-MAIN', 'NRW-MAIN', 'NRW-SGK'],
  },
  {
    id: 'PTN-YRG',
    name_th: 'จุดจอดรถโดยสาร อ.ยะหริ่ง',
    name_en: 'Yaring Bus Stop',
    province: 'pattani',
    district: 'อ.ยะหริ่ง',
    type: 'minor',
    lat: 6.8654,
    lng: 101.3654,
    description_th: 'บริเวณตลาดสด อ.ยะหริ่ง',
    description_en: 'At Yaring fresh market area',
    connections: ['PTN-MAIN'],
  },
  {
    id: 'PTN-NJK',
    name_th: 'จุดจอดรถโดยสาร อ.หนองจิก',
    name_en: 'Nong Chik Bus Stop',
    province: 'pattani',
    district: 'อ.หนองจิก',
    type: 'minor',
    lat: 6.8693,
    lng: 101.1647,
    description_th: 'แยกดอนยาง / วงเวียนหนองจิก — จุดเชื่อมต่อรถตู้สายหาดใหญ่-ปัตตานี-ยะลา',
    description_en: 'Don Yang junction — Hat Yai–Pattani–Yala van interchange',
    connections: ['PTN-MAIN', 'YLA-MAIN'],
  },
  {
    id: 'PTN-MYO',
    name_th: 'จุดจอดรถโดยสาร อ.มายอ',
    name_en: 'Mayo Bus Stop',
    province: 'pattani',
    district: 'อ.มายอ',
    type: 'minor',
    lat: 6.6842,
    lng: 101.2118,
    description_th: 'บริเวณตลาดสด อ.มายอ',
    description_en: 'At Mayo fresh market area',
    connections: ['PTN-MAIN', 'YLA-MAIN'],
  },
  {
    id: 'PTN-MKN',
    name_th: 'จุดจอดรถโดยสาร อ.ไม้แก่น',
    name_en: 'Mai Kaen Bus Stop',
    province: 'pattani',
    district: 'อ.ไม้แก่น',
    type: 'minor',
    lat: 6.6156,
    lng: 101.6412,
    description_th: 'บริเวณตัวอำเภอไม้แก่น',
    description_en: 'Mai Kaen district center',
    connections: ['PTN-SBR', 'NRW-SGK'],
  },
  
  // ── จุดจอดรายย่อย / คิวรถชุมชน (Local Stops) ──
  {
    id: 'PTN-PNR',
    name_th: 'คิวรถตู้ปะนาเระ / จุดจอดปาลัส',
    name_en: 'Panare / Palas Local Stop',
    province: 'pattani',
    district: 'อ.ปะนาเระ',
    type: 'local_stop',
    lat: 6.7465,
    lng: 101.4552,
    description_th: 'คิวรถย่อยและจุดแวะรับส่งชุมชน อ.ปะนาเระ (ตลาดปาลัส)',
    description_en: 'Informal van stop for Panare district & Palas market',
    connections: ['PTN-MAIN', 'PTN-MYO'],
  },
  {
    id: 'PTN-TYD',
    name_th: 'จุดจอดรถโดยสาร อ.ทุ่งยางแดง',
    name_en: 'Thung Yang Daeng Stop',
    province: 'pattani',
    district: 'อ.ทุ่งยางแดง',
    type: 'local_stop',
    lat: 6.5772,
    lng: 101.4428,
    description_th: 'จุดรับส่งรถตู้สายยะลา-ทุ่งยางแดง บริเวณชุมชน',
    description_en: 'Community pickup point for Yala-Thung Yang Daeng vans',
    connections: ['YLA-MAIN'],
  },
  {
    id: 'PTN-KPO',
    name_th: 'จุดจอดรถโดยสาร อ.กะพ้อ',
    name_en: 'Kapho Stop',
    province: 'pattani',
    district: 'อ.กะพ้อ',
    type: 'local_stop',
    lat: 6.5458,
    lng: 101.5540,
    description_th: 'จุดจอดรถตู้สายยะลา-กะพ้อ (กะลาพอ)',
    description_en: 'Informal stop for Yala-Kapho vans',
    connections: ['YLA-MAIN', 'PTN-TYD'],
  },
  {
    id: 'PTN-MLN',
    name_th: 'จุดจอดรถโดยสาร อ.แม่ลาน',
    name_en: 'Mae Lan Stop',
    province: 'pattani',
    district: 'อ.แม่ลาน',
    type: 'local_stop',
    lat: 6.6433,
    lng: 101.1711,
    description_th: 'จุดแวะรับส่งตามเส้นทางผ่านชุมชน อ.แม่ลาน',
    description_en: 'Roadside community stop in Mae Lan',
    connections: ['PTN-MAIN', 'YLA-MAIN'],
  },
  {
    id: 'PTN-BOTHONG',
    name_th: 'จุดจอดตลาดบ่อทอง (ลุงไข่บ่อทอง)',
    name_en: 'Bo Thong Market Stop',
    province: 'pattani',
    district: 'อ.หนองจิก',
    type: 'local_stop',
    lat: 6.8390,
    lng: 101.1390,
    description_th: 'จุดรับส่งย่อย/คิวรถสองแถว บริเวณตลาดบ่อทอง',
    description_en: 'Local market pickup point & songthaew stop',
    connections: ['PTN-NJK', 'PTN-MAIN'],
  },

  // ══════════════════════════════════════════════
  //  จังหวัดยะลา (YALA)
  // ══════════════════════════════════════════════

  // ── สถานีหลัก ──
  {
    id: 'YLA-MAIN',
    name_th: 'สถานีขนส่งผู้โดยสาร จ.ยะลา (บขส. ยะลา)',
    name_en: 'Yala Bus Terminal (BKS Yala)',
    province: 'yala',
    district: 'อ.เมืองยะลา',
    type: 'major',
    lat: 6.5496,
    lng: 101.2934,
    description_th: 'ถ.สิโรรส ต.สะเตง — สถานีขนส่งหลักของจังหวัดยะลา',
    description_en: 'Sirorot Road — Main bus terminal for Yala Province',
    connections: ['PTN-MAIN', 'NRW-MAIN', 'YLA-BTG', 'YLA-RMN', 'YLA-BNS', 'YLA-YHA'],
  },

  // ── สถานีย่อย / คิวรถ ──
  {
    id: 'YLA-BTG',
    name_th: 'สถานีขนส่งผู้โดยสาร อ.เบตง (บขส. เบตง)',
    name_en: 'Betong Bus Terminal (BKS Betong)',
    province: 'yala',
    district: 'อ.เบตง',
    type: 'major',
    lat: 5.7733,
    lng: 101.0605,
    description_th: 'รองรับรถทัวร์กรุงเทพฯ-เบตง รถตู้ยะลา-เบตง และหาดใหญ่-เบตง',
    description_en: 'Bangkok–Betong coach, Yala–Betong & Hat Yai–Betong van terminal',
    connections: ['YLA-MAIN', 'YLA-BTG-CLK', 'YLA-BNS', 'YLA-TRT'],
  },
  {
    id: 'YLA-BTG-CLK',
    name_th: 'คิวรถตู้ยะลา-เบตง (หอนาฬิกาเบตง)',
    name_en: 'Betong Clock Tower Van Stop',
    province: 'yala',
    district: 'อ.เบตง',
    type: 'minor',
    lat: 5.7735,
    lng: 101.0725,
    description_th: 'ใจกลางเมืองเบตง — จุดจอดรถตู้และรถแท็กซี่สายเบตง',
    description_en: 'Downtown Betong — van & taxi stop',
    connections: ['YLA-BTG'],
  },
  {
    id: 'YLA-TRAIN',
    name_th: 'คิวรถตู้ยะลา (หน้าสถานีรถไฟยะลา)',
    name_en: 'Yala Train Station Van Stop',
    province: 'yala',
    district: 'อ.เมืองยะลา',
    type: 'minor',
    lat: 6.5604,
    lng: 101.2927,
    description_th: 'คิวรถตู้ไปปัตตานี, นราธิวาส, หาดใหญ่, ยะหา',
    description_en: 'Van hub to Pattani, Narathiwat, Hat Yai & Yaha',
    connections: ['YLA-MAIN', 'PTN-MAIN', 'NRW-MAIN'],
  },
  {
    id: 'YLA-YHA',
    name_th: 'จุดจอดรถโดยสาร อ.ยะหา',
    name_en: 'Yaha Bus Stop',
    province: 'yala',
    district: 'อ.ยะหา',
    type: 'minor',
    lat: 6.4697,
    lng: 101.1242,
    description_th: 'บริเวณตลาดสด อ.ยะหา — รถตู้/รถสองแถวไปเมืองยะลา และกาบัง',
    description_en: 'Yaha market — van/songthaew to Yala & Kabang',
    connections: ['YLA-MAIN'],
  },
  {
    id: 'YLA-BNS',
    name_th: 'จุดจอดรถโดยสาร อ.บันนังสตา',
    name_en: 'Bannang Sata Bus Stop',
    province: 'yala',
    district: 'อ.บันนังสตา',
    type: 'minor',
    lat: 6.2468,
    lng: 101.1983,
    description_th: 'จุดพักรถสายยะลา-เบตง และรถสองแถวท้องถิ่น',
    description_en: 'Rest stop on Yala–Betong route & local songthaew',
    connections: ['YLA-MAIN', 'YLA-BTG', 'YLA-TRT'],
  },
  {
    id: 'YLA-RMN',
    name_th: 'จุดจอดรถโดยสาร อ.รามัน',
    name_en: 'Raman Bus Stop',
    province: 'yala',
    district: 'อ.รามัน',
    type: 'minor',
    lat: 6.5322,
    lng: 101.4185,
    description_th: 'หน้าสถานีรถไฟรามัน / ตลาดรามัน — รถสองแถว/รถตู้เข้าเมืองยะลา',
    description_en: 'Raman train station / market — songthaew/van to Yala',
    connections: ['YLA-MAIN', 'NRW-RSH'],
  },
  {
    id: 'YLA-TRT',
    name_th: 'จุดจอดรถโดยสาร อ.ธารโต',
    name_en: 'Than To Bus Stop',
    province: 'yala',
    district: 'อ.ธารโต',
    type: 'minor',
    lat: 6.0089,
    lng: 101.1547,
    description_th: 'หน้าที่ว่าการอำเภอธารโต — จุดจอดรถตู้สายยะลา-เบตง',
    description_en: 'Than To district office — van stop on Yala–Betong route',
    connections: ['YLA-BNS', 'YLA-BTG'],
  },

  // ── จุดจอดรายย่อย / คิวรถชุมชน (Local Stops) ──
  {
    id: 'YLA-KPN',
    name_th: 'จุดจอดรถโดยสาร อ.กรงปินัง',
    name_en: 'Krong Pinang Stop',
    province: 'yala',
    district: 'อ.กรงปินัง',
    type: 'local_stop',
    lat: 6.4385,
    lng: 101.2721,
    description_th: 'จุดแวะรับส่งชุมชนกรงปินัง ถนนสาย 410',
    description_en: 'Local stop on Route 410 for Krong Pinang',
    connections: ['YLA-MAIN', 'YLA-BNS'],
  },
  {
    id: 'YLA-KBG',
    name_th: 'คิวรถโดยสาร อ.กาบัง',
    name_en: 'Kabang Local Stop',
    province: 'yala',
    district: 'อ.กาบัง',
    type: 'local_stop',
    lat: 6.4253,
    lng: 101.0189,
    description_th: 'จุดจอดรถตู้/รถสองแถวสายยะลา-ยะหา-กาบัง',
    description_en: 'End of line for Yala-Yaha-Kabang local transport',
    connections: ['YLA-YHA'],
  },

  // ══════════════════════════════════════════════
  //  จังหวัดนราธิวาส (NARATHIWAT)
  // ══════════════════════════════════════════════

  // ── สถานีหลัก ──
  {
    id: 'NRW-MAIN',
    name_th: 'สถานีขนส่งผู้โดยสาร จ.นราธิวาส (บขส. นราธิวาส)',
    name_en: 'Narathiwat Bus Terminal (BKS Narathiwat)',
    province: 'narathiwat',
    district: 'อ.เมืองนราธิวาส',
    type: 'major',
    lat: 6.4109,
    lng: 101.8261,
    description_th: 'ถ.ระแงะมรรคา ต.บางนาค — สถานีขนส่งหลักของจังหวัดนราธิวาส',
    description_en: 'Rangae Makka Road — Main bus terminal for Narathiwat Province',
    connections: ['PTN-MAIN', 'YLA-MAIN', 'NRW-SGK', 'NRW-CLK', 'NRW-TKB', 'NRW-RNG'],
  },
  {
    id: 'NRW-SGK',
    name_th: 'สถานีขนส่งผู้โดยสาร อ.สุไหงโก-ลก (บขส. สุไหงโก-ลก)',
    name_en: 'Sungai Kolok Bus Terminal (BKS Sungai Kolok)',
    province: 'narathiwat',
    district: 'อ.สุไหงโก-ลก',
    type: 'major',
    lat: 6.0212,
    lng: 101.9492,
    description_th: 'สถานีใหญ่ชายแดน — รถทัวร์ตรงกรุงเทพฯ-สุไหงโก-ลก และรถข้ามไปมาเลเซีย',
    description_en: 'Border terminal — Bangkok–Sungai Kolok coach & Malaysia crossings',
    connections: ['NRW-MAIN', 'NRW-TKB', 'NRW-WNG'],
  },

  // ── สถานีย่อย / คิวรถ ──
  {
    id: 'NRW-CLK',
    name_th: 'คิวรถตู้ศูนย์การค้านราธิวาส (หอนาฬิกานราธิวาส)',
    name_en: 'Narathiwat Clock Tower Van Stop',
    province: 'narathiwat',
    district: 'อ.เมืองนราธิวาส',
    type: 'minor',
    lat: 6.4263,
    lng: 101.8198,
    description_th: 'คิวรถตู้ไปยะลา, ปัตตานี, สุไหงโก-ลก, ตากใบ',
    description_en: 'Van hub to Yala, Pattani, Sungai Kolok & Tak Bai',
    connections: ['NRW-MAIN', 'YLA-MAIN', 'PTN-MAIN', 'NRW-SGK', 'NRW-TKB'],
  },
  {
    id: 'NRW-TKB',
    name_th: 'จุดจอดรถโดยสาร อ.ตากใบ',
    name_en: 'Tak Bai Bus Stop',
    province: 'narathiwat',
    district: 'อ.ตากใบ',
    type: 'minor',
    lat: 6.2591,
    lng: 102.0447,
    description_th: 'บริเวณตลาดตากใบ / ใกล้ด่านตาบา — รถสองแถว/รถตู้ไปเมืองนราธิวาส',
    description_en: 'Tak Bai market / near Taba border — van/songthaew to Narathiwat',
    connections: ['NRW-MAIN', 'NRW-SGK'],
  },
  {
    id: 'NRW-BKT',
    name_th: 'จุดจอดรถโดยสาร ด่านพรมแดนบูเก๊ะตา',
    name_en: 'Bukit Ta Border Checkpoint Stop',
    province: 'narathiwat',
    district: 'อ.แว้ง',
    type: 'minor',
    lat: 5.9693,
    lng: 101.8651,
    description_th: 'จุดจอดรถตู้/สองแถวเชื่อมต่อด่านชายแดนแว้ง',
    description_en: 'Van/songthaew stop connecting Waeng border crossing',
    connections: ['NRW-WNG', 'NRW-SGK'],
  },
  {
    id: 'NRW-RNG',
    name_th: 'จุดจอดรถโดยสาร อ.ระแงะ (ตันหยงมัส)',
    name_en: 'Rangae (Tanyong Mat) Bus Stop',
    province: 'narathiwat',
    district: 'อ.ระแงะ',
    type: 'minor',
    lat: 6.3200,
    lng: 101.7283,
    description_th: 'หน้าสถานีรถไฟตันหยงมัส — จุดต่อรถตู้/สองแถวเข้าเมืองนราธิวาส',
    description_en: 'Tanyong Mat train station — van/songthaew to Narathiwat city',
    connections: ['NRW-MAIN', 'NRW-RSH'],
  },
  {
    id: 'NRW-RSH',
    name_th: 'จุดจอดรถโดยสาร อ.รือเสาะ',
    name_en: 'Rueso Bus Stop',
    province: 'narathiwat',
    district: 'อ.รือเสาะ',
    type: 'minor',
    lat: 6.3567,
    lng: 101.5376,
    description_th: 'หน้าสถานีรถไฟรือเสาะ / ตลาดรือเสาะ — คิวรถตู้ไปยะลา และเมืองนราธิวาส',
    description_en: 'Rueso train station / market — van hub to Yala & Narathiwat',
    connections: ['NRW-MAIN', 'YLA-MAIN', 'NRW-RNG'],
  },
  {
    id: 'NRW-YNG',
    name_th: 'จุดจอดรถโดยสาร อ.ยี่งอ',
    name_en: 'Yi-ngo Bus Stop',
    province: 'narathiwat',
    district: 'อ.ยี่งอ',
    type: 'minor',
    lat: 6.4523,
    lng: 101.7109,
    description_th: 'บริเวณทางแยกยี่งอ — จุดจอดรับ-ส่ง รถตู้และรถบัสสายปัตตานี-นราธิวาส',
    description_en: 'Yi-ngo junction — van & bus stop on Pattani–Narathiwat route',
    connections: ['NRW-MAIN', 'PTN-MAIN'],
  },
  {
    id: 'NRW-WNG',
    name_th: 'จุดจอดรถโดยสาร อ.แว้ง',
    name_en: 'Waeng Bus Stop',
    province: 'narathiwat',
    district: 'อ.แว้ง',
    type: 'minor',
    lat: 5.9387,
    lng: 101.8292,
    description_th: 'บริเวณตลาดสด อ.แว้ง',
    description_en: 'At Waeng fresh market area',
    connections: ['NRW-SGK', 'NRW-BKT'],
  },
  {
    id: 'NRW-SKR',
    name_th: 'จุดจอดรถโดยสาร อ.สุคิริน',
    name_en: 'Sukhirin Bus Stop',
    province: 'narathiwat',
    district: 'อ.สุคิริน',
    type: 'minor',
    lat: 5.9803,
    lng: 101.7056,
    description_th: 'ส่วนใหญ่เป็นรถสองแถวท้องถิ่นไปสุไหงโก-ลก',
    description_en: 'Mostly local songthaew to Sungai Kolok',
    connections: ['NRW-SGK'],
  },
  {
    id: 'NRW-SSK',
    name_th: 'จุดจอดรถโดยสาร อ.ศรีสาคร',
    name_en: 'Si Sakhon Bus Stop',
    province: 'narathiwat',
    district: 'อ.ศรีสาคร',
    type: 'minor',
    lat: 6.3084,
    lng: 101.6138,
    description_th: 'รถสองแถว/รถตู้เข้าเมืองนราธิวาสและรือเสาะ',
    description_en: 'Songthaew/van to Narathiwat city & Rueso',
    connections: ['NRW-MAIN', 'NRW-RSH'],
  },

  // ── จุดจอดรายย่อย / คิวรถชุมชน (Local Stops) ──
  {
    id: 'NRW-CAR',
    name_th: 'คิวรถโดยสาร อ.เจาะไอร้อง',
    name_en: 'Cho-airong Stop',
    province: 'narathiwat',
    district: 'อ.เจาะไอร้อง',
    type: 'local_stop',
    lat: 6.2081,
    lng: 101.8398,
    description_th: 'จุดรับส่งรถสองแถว/รถตู้ หน้าสถานีรถไฟเจาะไอร้อง',
    description_en: 'Local stop near Cho-airong train station',
    connections: ['NRW-MAIN', 'NRW-SGK'],
  },
  {
    id: 'NRW-SGP',
    name_th: 'คิวรถโดยสาร อ.สุไหงปาดี',
    name_en: 'Sungai Padi Stop',
    province: 'narathiwat',
    district: 'อ.สุไหงปาดี',
    type: 'local_stop',
    lat: 6.0886,
    lng: 101.8845,
    description_th: 'จุดรับส่งรถสองแถว/รถตู้ หน้าสถานีรถไฟสุไหงปาดี',
    description_en: 'Local stop near Sungai Padi train station',
    connections: ['NRW-SGK'],
  },
  {
    id: 'NRW-BCO',
    name_th: 'จุดจอดรถโดยสาร อ.บาเจาะ',
    name_en: 'Bacho Stop',
    province: 'narathiwat',
    district: 'อ.บาเจาะ',
    type: 'local_stop',
    lat: 6.5168,
    lng: 101.6565,
    description_th: 'จุดรับส่งรถสายปัตตานี-นราธิวาส บริเวณตลาดบาเจาะ',
    description_en: 'Stop on Pattani-Narathiwat route at Bacho market',
    connections: ['NRW-MAIN', 'PTN-MAIN'],
  },
  {
    id: 'NRW-CNE',
    name_th: 'จุดจอดรถโดยสาร อ.จะแนะ',
    name_en: 'Chanae Stop',
    province: 'narathiwat',
    district: 'อ.จะแนะ',
    type: 'local_stop',
    lat: 6.0967,
    lng: 101.7058,
    description_th: 'จุดจอดรถสองแถวท้องถิ่นเข้าตัวอำเภอจะแนะ',
    description_en: 'Local songthaew stop in Chanae',
    connections: ['NRW-RNG'],
  }
];

// ── Route Lines (เส้นทางเชื่อมต่อ) ──
export interface RouteConnection {
  id: string;
  name_th: string;
  name_en: string;
  color: string;
  stationIds: string[];
}

export const ROUTE_CONNECTIONS: RouteConnection[] = [
  {
    id: 'R-PTN-YLA',
    name_th: 'สายปัตตานี — ยะลา',
    name_en: 'Pattani — Yala Route',
    color: '#10B981',
    stationIds: ['PTN-MAIN', 'PTN-NJK', 'PTN-KPH', 'PTN-MYO', 'YLA-MAIN'],
  },
  {
    id: 'R-PTN-NRW',
    name_th: 'สายปัตตานี — นราธิวาส',
    name_en: 'Pattani — Narathiwat Route',
    color: '#3B82F6',
    stationIds: ['PTN-MAIN', 'PTN-YRG', 'PTN-SBR', 'NRW-YNG', 'NRW-MAIN'],
  },
  {
    id: 'R-YLA-BTG',
    name_th: 'สายยะลา — เบตง',
    name_en: 'Yala — Betong Route',
    color: '#F59E0B',
    stationIds: ['YLA-MAIN', 'YLA-YHA', 'YLA-BNS', 'YLA-TRT', 'YLA-BTG'],
  },
  {
    id: 'R-YLA-NRW',
    name_th: 'สายยะลา — นราธิวาส',
    name_en: 'Yala — Narathiwat Route',
    color: '#8B5CF6',
    stationIds: ['YLA-MAIN', 'YLA-RMN', 'NRW-RSH', 'NRW-RNG', 'NRW-MAIN'],
  },
  {
    id: 'R-NRW-SGK',
    name_th: 'สายนราธิวาส — สุไหงโก-ลก',
    name_en: 'Narathiwat — Sungai Kolok Route',
    color: '#EF4444',
    stationIds: ['NRW-MAIN', 'NRW-RNG', 'NRW-WNG', 'NRW-SGK'],
  },
  {
    id: 'R-NRW-TKB',
    name_th: 'สายนราธิวาส — ตากใบ',
    name_en: 'Narathiwat — Tak Bai Route',
    color: '#EC4899',
    stationIds: ['NRW-MAIN', 'NRW-TKB'],
  },
];

// สีตามจังหวัด
export const PROVINCE_COLORS: Record<Province, string> = {
  pattani: '#10B981',    // เขียว
  yala: '#F59E0B',       // เหลือง
  narathiwat: '#3B82F6', // ฟ้า
};
